[package]
name = "demoos"
version = "0.1.0"
edition = "2021"

[dependencies]
aarch64-paging = { version = "0.7.1", default-features = false }
arm_pl031 = "0.2.1"
arm-gic = "0.1.0"
arrayvec = { version = "0.7.4", default-features = false }
bitflags = "2.6.0"
buddy_system_allocator = { version = "0.10.0", default-features = false, features = [
  "alloc",
  "use_spin",
] }
chrono = { version = "0.4.38", default-features = false }
embedded-io = "0.6.1"
flat_device_tree = { version = "3.1.1", features = ["pretty-printing"] }
log = "0.4.22"
percore = "0.1.0"
smccc = "0.1.1"
spin = { version = "0.9.8", features = [
  "spin_mutex",
  "once",
], default-features = false }
virtio-drivers = { version = "0.7.5", default-features = false, features = [
  "alloc",
] }

[build-dependencies]
cc = "1.1.5"
