[package]
name = "demoos"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
chrono = { version = "0.4.38", default-features = false }
embedded-io = "0.6.1"
log = "0.4.22"
smccc = "0.1.1"
spin = { version = "0.9.8", features = ["once"] }
tinyvec = "1.8.0"

[build-dependencies]
cc = "1.1.5"

[features]
plat-qemu = []
default = ["plat-qemu"]
